-- Starter recipes. Safe to re-run: existing ids are updated in place.
insert into public.recipes (id, name, cuisine, protein, minutes, effort, vibes, vegetarian, why, ingredients, steps) values
  (1, 'Cacio e Pepe', 'Italian', 'veg', 20, 2, array['comfort', 'cozy'], true, 'Finishing the pasta off the heat with starchy water keeps the cheese from clumping and turns it into a glossy sauce.', array['200g spaghetti', '1 cup finely grated pecorino', '1 tbsp black peppercorns, cracked', 'Salt', 'Pasta water'], array['Toast cracked pepper in a dry pan 1 minute.', 'Boil pasta in salted water, reserve 1 cup water, drain 2 minutes early.', 'Finish pasta in the pepper pan with a ladle of water.', 'Off the heat, toss in cheese with splashes of water until glossy.']),
  (2, 'Chicken Piccata', 'Italian', 'chicken', 30, 2, array['fresh'], false, 'A thin dusting of flour browns the cutlets and thickens the pan sauce at the same time.', array['2 chicken cutlets', 'Flour for dredging', '2 lemons', '2 tbsp capers', '1/2 cup chicken stock', 'Butter'], array['Season and flour the cutlets, sear 3 minutes per side, set aside.', 'Add stock, lemon juice and capers; reduce by half.', 'Swirl in butter, return chicken, spoon sauce over.']),
  (3, 'Chicken Tinga Tacos', 'Mexican', 'chicken', 35, 2, array['spicy', 'comfort'], false, 'Poaching thighs first keeps them juicy, and the smoky chipotle sauce clings to the shredded meat.', array['500g chicken thighs', '2 chipotles in adobo', '1 can crushed tomatoes', '1 onion', 'Corn tortillas', 'Lime and cilantro'], array['Simmer chicken in water with half the onion 20 minutes, shred.', 'Blend tomatoes, chipotles and remaining onion; simmer 10 minutes.', 'Fold in chicken, serve in warm tortillas with lime.']),
  (4, 'Black Bean Quesadillas', 'Mexican', 'veg', 15, 1, array['quick', 'comfort'], true, 'Mashing the beans makes a spreadable filling that holds together instead of sliding out.', array['1 can black beans', '4 flour tortillas', '1.5 cups shredded cheese', 'Cumin', 'Salsa'], array['Mash beans with cumin and a pinch of salt.', 'Fill tortillas with beans and cheese.', 'Griddle 2 minutes per side until crisp; serve with salsa.']),
  (5, 'Green Curry with Shrimp', 'Thai', 'seafood', 30, 2, array['spicy', 'cozy'], false, 'Frying the paste in coconut cream first wakes up its aromatics before the liquid goes in.', array['3 tbsp green curry paste', '1 can coconut milk', '400g shrimp', 'Thai basil', '1 zucchini', 'Fish sauce and lime'], array['Fry the paste in a spoon of coconut cream 1 minute.', 'Add remaining milk and zucchini, simmer 8 minutes.', 'Add shrimp until pink, finish with fish sauce, lime and basil.']),
  (6, 'Pad See Ew', 'Thai', 'beef', 25, 2, array['comfort'], false, 'A ripping-hot pan and a small batch give the noodles their smoky, charred edges.', array['Wide rice noodles', '200g sliced beef', 'Chinese broccoli', '2 eggs', 'Dark and light soy', 'Oyster sauce'], array['Sear beef in a very hot wok, push aside.', 'Scramble eggs, add greens and noodles.', 'Toss with soy and oyster sauce until charred at the edges.']),
  (7, 'Chana Masala', 'Indian', 'veg', 35, 2, array['cozy', 'spicy'], true, 'Blooming the spices in oil and mashing a few chickpeas builds a thick, deeply flavored sauce from pantry staples.', array['2 cans chickpeas', '1 onion', 'Ginger and garlic', '1 can tomatoes', '2 tbsp garam masala', 'Cilantro'], array['Brown the onion, add ginger, garlic and spices for 1 minute.', 'Add tomatoes and chickpeas, simmer 20 minutes.', 'Mash a few chickpeas to thicken; finish with cilantro.']),
  (8, 'Butter Chicken', 'Indian', 'chicken', 45, 3, array['comfort', 'cozy'], false, 'A yogurt marinade tenderizes the chicken, and charring it adds the smokiness a tandoor would.', array['600g chicken thighs', '1 cup yogurt', 'Garam masala', '1 can tomato purée', '1/2 cup cream', '4 tbsp butter'], array['Marinate chicken in yogurt and spices, ideally an hour.', 'Broil or sear until charred.', 'Simmer tomato, butter and spices 15 minutes; add cream and chicken.']),
  (9, 'Miso Salmon Rice Bowl', 'Japanese', 'seafood', 20, 1, array['quick', 'fresh'], false, 'Miso''s sugars caramelize fast under high heat, so a two-ingredient rub does the work of a long marinade.', array['2 salmon fillets', '2 tbsp white miso', '1 tbsp mirin', 'Cooked rice', 'Cucumber', 'Sesame seeds'], array['Rub salmon with miso and mirin.', 'Roast at 220°C for 10 minutes.', 'Serve over rice with sliced cucumber and sesame.']),
  (10, 'Chicken Katsu Curry', 'Japanese', 'chicken', 40, 3, array['comfort', 'cozy'], false, 'Pounding the chicken thin means it cooks in the time it takes the panko to turn golden.', array['2 chicken breasts', 'Panko, flour, egg', 'Curry roux block', '1 carrot, 1 onion', 'Rice'], array['Simmer carrot and onion in water, melt in roux.', 'Bread the pounded chicken: flour, egg, panko.', 'Shallow-fry 3 minutes per side; slice over rice and ladle sauce.']),
  (11, 'Smash Burgers', 'American', 'beef', 20, 1, array['comfort', 'quick'], false, 'Smashing loosely packed beef onto a very hot pan maximizes browned, crispy surface area.', array['400g ground beef', '4 potato buns', 'American cheese', 'Pickles', 'Onion', 'Burger sauce'], array['Roll beef into 4 loose balls.', 'Smash hard onto a screaming-hot pan, season, cook 2 minutes.', 'Flip, add cheese, stack on toasted buns.']),
  (12, 'Sheet-Pan Sausage and Veg', 'American', 'beef', 35, 1, array['quick', 'cozy'], false, 'Cutting everything to a similar size and roasting hot means one pan and one timer.', array['4 sausages', '2 potatoes', '1 red onion', 'Broccoli', 'Olive oil, mustard'], array['Chop everything into bite-size pieces, toss in oil.', 'Roast at 220°C for 25 minutes, flipping once.', 'Drizzle with mustard.']),
  (13, 'Lemony Chickpea Salad', 'Mediterranean', 'veg', 10, 1, array['fresh', 'quick'], true, 'Dressing the chickpeas while the vegetables are being chopped lets them soak up flavor.', array['1 can chickpeas', 'Cucumber', 'Cherry tomatoes', 'Red onion', 'Feta', 'Lemon and olive oil'], array['Chop the vegetables.', 'Toss with chickpeas, lemon and oil.', 'Crumble feta over the top.']),
  (14, 'Shakshuka', 'Mediterranean', 'egg', 25, 1, array['cozy', 'spicy'], true, 'Cooking the tomatoes down first gives the eggs a thick sauce to nestle in, so the whites set before the yolks harden.', array['4 eggs', '1 can tomatoes', '1 pepper', '1 onion', 'Cumin and paprika', 'Crusty bread'], array['Soften onion and pepper with the spices.', 'Add tomatoes, simmer 10 minutes.', 'Crack in eggs, cover, cook until whites set.']),
  (15, 'Egg Fried Rice', 'Chinese', 'egg', 15, 1, array['quick', 'comfort'], true, 'Day-old rice is drier, so the grains fry and separate instead of clumping.', array['3 cups day-old rice', '3 eggs', 'Frozen peas', 'Scallions', 'Soy sauce', 'Sesame oil'], array['Scramble the eggs in a hot wok, set aside.', 'Fry rice until it jumps and crackles.', 'Return eggs, add peas, soy and sesame oil.']),
  (16, 'Mapo Tofu', 'Chinese', 'tofu', 30, 2, array['spicy', 'comfort'], true, 'Frying the chile paste until the oil turns red builds the sauce''s deep flavor before the tofu goes in.', array['1 block soft tofu', '2 tbsp doubanjiang', '150g ground pork or mushrooms', 'Sichuan peppercorns', 'Scallions', 'Cornstarch slurry'], array['Fry the paste and pork until the oil turns red.', 'Add stock and tofu cubes, simmer 5 minutes.', 'Thicken with slurry, top with peppercorns and scallions.'])
on conflict (id) do update set
  name=excluded.name, cuisine=excluded.cuisine, protein=excluded.protein, minutes=excluded.minutes,
  effort=excluded.effort, vibes=excluded.vibes, vegetarian=excluded.vegetarian, why=excluded.why,
  ingredients=excluded.ingredients, steps=excluded.steps;
