// Built-in recipes. Used when Supabase is not configured or unreachable.
// The same data is loaded into the database by supabase/seed.sql.
window.RECIPES = [
  {"n":"Cacio e Pepe","c":"Italian","p":"veg","t":20,"e":2,"v":["comfort","cozy"],"veg":1,"w":"Finishing the pasta off the heat with starchy water keeps the cheese from clumping and turns it into a glossy sauce.","i":["200g spaghetti","1 cup finely grated pecorino","1 tbsp black peppercorns, cracked","Salt","Pasta water"],"s":["Toast cracked pepper in a dry pan 1 minute.","Boil pasta in salted water, reserve 1 cup water, drain 2 minutes early.","Finish pasta in the pepper pan with a ladle of water.","Off the heat, toss in cheese with splashes of water until glossy."],"id":1},
  {"n":"Chicken Piccata","c":"Italian","p":"chicken","t":30,"e":2,"v":["fresh"],"w":"A thin dusting of flour browns the cutlets and thickens the pan sauce at the same time.","i":["2 chicken cutlets","Flour for dredging","2 lemons","2 tbsp capers","1/2 cup chicken stock","Butter"],"s":["Season and flour the cutlets, sear 3 minutes per side, set aside.","Add stock, lemon juice and capers; reduce by half.","Swirl in butter, return chicken, spoon sauce over."],"id":2},
  {"n":"Chicken Tinga Tacos","c":"Mexican","p":"chicken","t":35,"e":2,"v":["spicy","comfort"],"w":"Poaching thighs first keeps them juicy, and the smoky chipotle sauce clings to the shredded meat.","i":["500g chicken thighs","2 chipotles in adobo","1 can crushed tomatoes","1 onion","Corn tortillas","Lime and cilantro"],"s":["Simmer chicken in water with half the onion 20 minutes, shred.","Blend tomatoes, chipotles and remaining onion; simmer 10 minutes.","Fold in chicken, serve in warm tortillas with lime."],"id":3},
  {"n":"Black Bean Quesadillas","c":"Mexican","p":"veg","t":15,"e":1,"v":["quick","comfort"],"veg":1,"w":"Mashing the beans makes a spreadable filling that holds together instead of sliding out.","i":["1 can black beans","4 flour tortillas","1.5 cups shredded cheese","Cumin","Salsa"],"s":["Mash beans with cumin and a pinch of salt.","Fill tortillas with beans and cheese.","Griddle 2 minutes per side until crisp; serve with salsa."],"id":4},
  {"n":"Green Curry with Shrimp","c":"Thai","p":"seafood","t":30,"e":2,"v":["spicy","cozy"],"w":"Frying the paste in coconut cream first wakes up its aromatics before the liquid goes in.","i":["3 tbsp green curry paste","1 can coconut milk","400g shrimp","Thai basil","1 zucchini","Fish sauce and lime"],"s":["Fry the paste in a spoon of coconut cream 1 minute.","Add remaining milk and zucchini, simmer 8 minutes.","Add shrimp until pink, finish with fish sauce, lime and basil."],"id":5},
  {"n":"Pad See Ew","c":"Thai","p":"beef","t":25,"e":2,"v":["comfort"],"w":"A ripping-hot pan and a small batch give the noodles their smoky, charred edges.","i":["Wide rice noodles","200g sliced beef","Chinese broccoli","2 eggs","Dark and light soy","Oyster sauce"],"s":["Sear beef in a very hot wok, push aside.","Scramble eggs, add greens and noodles.","Toss with soy and oyster sauce until charred at the edges."],"id":6},
  {"n":"Chana Masala","c":"Indian","p":"veg","t":35,"e":2,"v":["cozy","spicy"],"veg":1,"w":"Blooming the spices in oil and mashing a few chickpeas builds a thick, deeply flavored sauce from pantry staples.","i":["2 cans chickpeas","1 onion","Ginger and garlic","1 can tomatoes","2 tbsp garam masala","Cilantro"],"s":["Brown the onion, add ginger, garlic and spices for 1 minute.","Add tomatoes and chickpeas, simmer 20 minutes.","Mash a few chickpeas to thicken; finish with cilantro."],"id":7},
  {"n":"Butter Chicken","c":"Indian","p":"chicken","t":45,"e":3,"v":["comfort","cozy"],"w":"A yogurt marinade tenderizes the chicken, and charring it adds the smokiness a tandoor would.","i":["600g chicken thighs","1 cup yogurt","Garam masala","1 can tomato purée","1/2 cup cream","4 tbsp butter"],"s":["Marinate chicken in yogurt and spices, ideally an hour.","Broil or sear until charred.","Simmer tomato, butter and spices 15 minutes; add cream and chicken."],"id":8},
  {"n":"Miso Salmon Rice Bowl","c":"Japanese","p":"seafood","t":20,"e":1,"v":["quick","fresh"],"w":"Miso's sugars caramelize fast under high heat, so a two-ingredient rub does the work of a long marinade.","i":["2 salmon fillets","2 tbsp white miso","1 tbsp mirin","Cooked rice","Cucumber","Sesame seeds"],"s":["Rub salmon with miso and mirin.","Roast at 220°C for 10 minutes.","Serve over rice with sliced cucumber and sesame."],"id":9},
  {"n":"Chicken Katsu Curry","c":"Japanese","p":"chicken","t":40,"e":3,"v":["comfort","cozy"],"w":"Pounding the chicken thin means it cooks in the time it takes the panko to turn golden.","i":["2 chicken breasts","Panko, flour, egg","Curry roux block","1 carrot, 1 onion","Rice"],"s":["Simmer carrot and onion in water, melt in roux.","Bread the pounded chicken: flour, egg, panko.","Shallow-fry 3 minutes per side; slice over rice and ladle sauce."],"id":10},
  {"n":"Smash Burgers","c":"American","p":"beef","t":20,"e":1,"v":["comfort","quick"],"w":"Smashing loosely packed beef onto a very hot pan maximizes browned, crispy surface area.","i":["400g ground beef","4 potato buns","American cheese","Pickles","Onion","Burger sauce"],"s":["Roll beef into 4 loose balls.","Smash hard onto a screaming-hot pan, season, cook 2 minutes.","Flip, add cheese, stack on toasted buns."],"id":11},
  {"n":"Sheet-Pan Sausage and Veg","c":"American","p":"beef","t":35,"e":1,"v":["quick","cozy"],"w":"Cutting everything to a similar size and roasting hot means one pan and one timer.","i":["4 sausages","2 potatoes","1 red onion","Broccoli","Olive oil, mustard"],"s":["Chop everything into bite-size pieces, toss in oil.","Roast at 220°C for 25 minutes, flipping once.","Drizzle with mustard."],"id":12},
  {"n":"Lemony Chickpea Salad","c":"Mediterranean","p":"veg","t":10,"e":1,"v":["fresh","quick"],"veg":1,"w":"Dressing the chickpeas while the vegetables are being chopped lets them soak up flavor.","i":["1 can chickpeas","Cucumber","Cherry tomatoes","Red onion","Feta","Lemon and olive oil"],"s":["Chop the vegetables.","Toss with chickpeas, lemon and oil.","Crumble feta over the top."],"id":13},
  {"n":"Shakshuka","c":"Mediterranean","p":"egg","t":25,"e":1,"v":["cozy","spicy"],"veg":1,"w":"Cooking the tomatoes down first gives the eggs a thick sauce to nestle in, so the whites set before the yolks harden.","i":["4 eggs","1 can tomatoes","1 pepper","1 onion","Cumin and paprika","Crusty bread"],"s":["Soften onion and pepper with the spices.","Add tomatoes, simmer 10 minutes.","Crack in eggs, cover, cook until whites set."],"id":14},
  {"n":"Egg Fried Rice","c":"Chinese","p":"egg","t":15,"e":1,"v":["quick","comfort"],"veg":1,"w":"Day-old rice is drier, so the grains fry and separate instead of clumping.","i":["3 cups day-old rice","3 eggs","Frozen peas","Scallions","Soy sauce","Sesame oil"],"s":["Scramble the eggs in a hot wok, set aside.","Fry rice until it jumps and crackles.","Return eggs, add peas, soy and sesame oil."],"id":15},
  {"n":"Mapo Tofu","c":"Chinese","p":"tofu","t":30,"e":2,"v":["spicy","comfort"],"veg":1,"w":"Frying the chile paste until the oil turns red builds the sauce's deep flavor before the tofu goes in.","i":["1 block soft tofu","2 tbsp doubanjiang","150g ground pork or mushrooms","Sichuan peppercorns","Scallions","Cornstarch slurry"],"s":["Fry the paste and pork until the oil turns red.","Add stock and tofu cubes, simmer 5 minutes.","Thicken with slurry, top with peppercorns and scallions."],"id":16}
];
